[package]
name = "pathos"
version = "0.1.0"
authors = ["Tomáš Svoboda <svoboda@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
